 vigenere_cipher_example.c

/*
  This program implements a vigenere cipher 
  It encrypts the message "vigenerecipher" using the key "small"
  Note the use of ASCII table
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main()
{
   unsigned long int i;

   char *message="vigenerecipher";  /*the plaintext*/
   char *key="small";               /*the key*/
   int keylen;                      /*the key length*/

   unsigned char temp;              /*the value of the current plaintext letter*/
   unsigned char currentkeylettervalue; /*the value of the current key letter*/
   unsigned char ciphertextlettervalue; /*the value of the current ciphertext letter*/


   keylen = strlen(key);   /*find the key length*/


   /*encrypt the plaintext letter by letter, and print out the ciphertext letter*/
   for(i = 0; i < strlen(message); i++)
   {
      /*convert the value of the plaintext letter, according to the ASCII table*/
      if (message[i] >= 97) temp = message[i] - 97;  
      else temp = message[i] - 65;   
      
      /*determine the value of the current key letter*/
      if (key[i % keylen] >= 97) currentkeylettervalue = key[i % keylen] - 97; 
      else currentkeylettervalue = key[i % keylen] - 65;

      /*encryption: find the value of the ciphertext letter*/
      ciphertextlettervalue = (temp + currentkeylettervalue) % 26;

      /*print ciphertext letter: add 65 so as to get the letter in the ASCII table*/
      printf("%c",ciphertextlettervalue + 65); 
   }

   return 0;
}




(Substitution)The ciphertext is: 

JOZYMAZJAJKAWZOYSMZQYWJZAVKMCXEKWYWYEUWAZMDAXZJTYYBAXKAAXYVOKMUQYWOURYKISMCKRYMAKNFKWWZYWAUAXYOUMAZMSYCWKEZCRZMZKASWZLKAZUMUIOURESAYWRYRUWVAXKAXKJFYYMAXYFKJZJIUWAXYOUMJSRYWYNYOAWUMZOJWYQUNSAZUMZMWYOYMAVYKWJAXYNZRZAJUIEXVJZOJKMCIZMKMOYIKOYCFVOXZERKBYWJXKCNUURYCJUNKWDYAXKAYGEYWAJIYKWYCKJNUTCUTMZMAXYEKOYUIRZMZKASWZLKAZUMAXKATUSNCKOANZBYKFWKBYUMAXYKFZNZAVAUEKOBYQYWRUWYEUTYWZMAUYQYWJRKNNYWCYQZOYJNZBYNKEAUEJJRKWAEXUMYJKMCCZDZAKNOKRYWKJFSAAXYMYTKMMUSMOYRYMAJKNUMDTZAXOUREYAZMDAYOXMUNUDZYJFYZMDESWJSYCFVOUREKMZYJNZBYZFRKMCZMAYNUIIYWXUEYAXKAAXYFWKBYTZNNMUAFYKEENZYCKMVAZRYJUUMZMUMYUIAXYATUMYTCYQYNUERYMAJWZOYWYJYKWOXYWJKWYWYEUWAZMDZMMKMUNYAAYWJKPUSWMKNUIAXYKRYWZOKMOXYRZOKNJUOZYAVAXKAAXYVXKQYJSOOYYCYCZMFSZNCZMDWYNZKFNYJRKNNCZDZAKNJTZAOXYJKMYJJYMAZKNEKWAUIOURESAYWRYRUWVAXKAOUSNCJXWZMBAUKJZDMZIZOKMANVJRKNNYWJOKNYAXKMZJEUJJZFNYSJZMDOUMQYMAZUMKNRYAXUCJRUWYZREUWAKMAAXYKCQKMOYZJFKJYCUMJZNZOUMUGZCYUMYUIAXYFKJZOFSZNCZMDFNUOBJUIAUCKVJOXZEZMCSJAWVAXSJYKJZMDKRUQYAUTKWCOURRYWOZKNZLKAZUMAXYJOZYMAZJAJJKZCAXKAEWZQKAWKMKAYGKJJAKWASEOUREKMVXKJRKCYYGEYWZRYMAKNOXZEJSJZMDAXYAYOXMZHSYAXKAOKMJAUWYKMCWYAWZYQYZMIUWRKAZUMAXZJZJJURYAXZMDAXKAZFRJASCZYCFYIUWYKMCTXZOXZJJAZNNZMAXYWYJYKWOXJAKDYJKZCOXKWNYJNKRKMZFRJEYOZKNZJAZMJYRZOUMCSOAUWRYRUWZYJXEXKJIUWJYQYWKNVYKWJFYYMRKBZMDONKZRJAXKAZAJRYRWZJAUWAYOXMUNUDVOKMOUREYAYTZAXAWKCZAZUMKNAWKMJZJAUWJFSAAXYOUREKMVTZNNWYEUWAAXZJTYYBAXKAZAZJMUTRUWYOUMIZCYMAAXKAZAJAYOXMUNUDVOKMOUREYAYOURRYWOZKNNVZMAXYISASWYZMOUMAWKJAAXYWZOYKCQKMOYRSJAJAZNNFYEWUQYCKOBMUTNYCDZMDAXKAWYJYKWOXYWJRSJAUQYWOURYJBYEAZOZJRFYOKSJYJZNZOUMUGZCYXKJFYYMBMUTMKJKMZMJSNKAUWFVAXYZMCSJAWVSMAZNMUTPZRAUSWKMKMURKAYWZKNJJEYOZKNZJAKAWZOYJKZCXYFYNZYQYCAXYZMCSJAWVTUSNCXKQYAUNUUBJYWZUSJNVKAAXYWYJYKWOXAYKRJMYTKEEWUKOXZAJKXKWCJYNNFYOKSJYKAIZWJAZAJUFQZUSJZATUMATUWBXYJKZCFSARVXUEYZJAXKAAXZJZJJUJZRENYAXYVTZNNXKQYAUESAZAZMAXYZWEUWAIUNZUAUYGENUWY



(Vigenere)The ciphertext is:
JMGPUYCOJYNVDCAVFGXWHXYIAZJRLVJWLKFXLKFFTTHSLVJPOKFGNROOUWFGXWHXYIADZHYIAWNLWYBSKDQWXMGPRSWVQEZXNBJRSIXEKODYBOVWTVNPWUYSXDZHWXHZWVTJVKDZFVNSFFQYMSFJGYCXGWQMVSLHIXXKVZFVNKFGXTHGSUJTAYYUFQBDZDYHXXGWMEEOLKJVNZJRIYLDAYJEKSDLYCJDJXJZRBMVHEWCHUJEMPJRRSWOURRTDDWUYSJXGWMIASFVTQNPGURSOOPHHYCKTOJGXNWZMIWSLVMSBDAVYETOFWTXQOLDWKNDURRTDDWUKSASFVYEWMWEJGJEKHFYBOJVJRCSLRAIAKFHYAXBCRWXQOAQYIAXWWTVLKJUNIMSLRSEAOERAEKVWPJHREEVZGQKKDKPXZHBIMBUUGIZMYJXXFMBAYJZRBMVJWLKFLSGAOSVJXQOAUHLJXUHXSOCHUJEMSFJYSXDZHWGXWHXYIACTBNROOUWNRPPAOJWXXSQJXFYJNKMUOKBXXNWGUFJRVWVDWCOEWMECSKDHGNCKHIFHKFRYLNBURRTDDWUFWBDSWJHJLGYJXQOLHWQLYESZXNBNLWYBSKVTQNDAPJWDCWGFWJMSWHLJVDSMVJCWWTMWMDXIIJVDWDTNCGIREUGSUJIEOFWMSBOLKFXMYFRYLJFWWMIAOHUTHDMLLAIJLAONXHWSOBEAOAQHPDNWVHSVZMWJVESJXXIBMGPUYCOJZTVVCLUTNJXZRWWNCERXXAYGWPMCCKSDAJBWGNWQYFHXXJNODWIJXVRYLNBEDQMLSGXXEWNMQBEWDWGXSODODWIRXUOZHRXYWWYNFAUZWNCNLWYBOKDWIBYEHYMVOKFTROEKHIARDZZTVVCSQIXAYBDSLXBKHXAQSUKFVNDWFMRRMSOQCMSXIJVNXLDBSAWUDSIGZDRNXBOUXWMCINXQRNBSENPRDAHXXXCHUJEMSLVJPOKMWTQJDAFFPUILRTXQOJFTQYELHWWCRJRZKQXWWBSAUKZMMUOSWWSSKFKTVBOAVFTAYYUFQCRSWFTYOSUXLJBEOJWBLMWMMMOKPFPRMARZWOEFFYMXXKZTVVCSQIXAYBDSLXBKHXPRUWYNVDCWVREHRSURELYESZXNBKBXXNWKGFXJYJSJVOYJPFRLOKRRIESJXXIBKFGTXQOJPFPFKJHMEEOKBRTCYEVSSCSUHFFUOLRYLNMGPUYCOJXXIALMWREWISUJWDBJHUXRDARZWXBKLRTUIVRSSCRAQLXXMSOQECDWQYMXXLRYLNWKHQZNCKRRIESJXXIBNGQTXQSFJGIHYFGWIYBGGZGRXYWMIVCWOAIBDZHKMACLDHEMOELHAXBCRSXQOLKJSAIGIHSVZMWJVESJXXIBKDWMSDQZWMICOJPHSVZMWJVESJXXAJCFRYMWFWQYIMKLWMECDAPJAJCVRSIKIBRMREYFQJYVKFQBLXRWOIPNMLXWIBKLWMIDXAYJVBSLBTJRVDLSSRCSETYCDZHYLNYJBFRMYJJFRRJSWNSWYXFTQYVAFFXNNSXYSVKLDYLNGGUPSOFGQSIDWSQSAJCDDYIAZMEQMBRWGFWCRWWMIXBQRKWNVXUJTAYVXHMWQSXYSVKLDNRQSKHXWJINRSRNEEDSRYYKWZPJDWGYLJDSFTQYELHWTAYYUFQLYMOIVNZJRIYLO



