
title: Shuhao Zhang's Homepage
page-top-title: Shuhao Zhang
top-section-bg-text: 动态环境下的数据密集型系统<br>执行与服务优化
description: 张书豪，华中科技大学教授。研究动态环境下的数据密集型系统，围绕任务执行、信息维护与在线服务调控开展系统研究。
home-subtitle: Shuhao Zhang &ensp;|&ensp; 张书豪
