
title: Shuhao Zhang's Homepage
page-top-title: Shuhao Zhang
top-section-bg-text: 面向国产算力的<br>极致性能推理引擎
description: 张书豪，华中科技大学教授。以面向国产算力的极致性能推理引擎为系统内核，面向智能体应用构建持续数据与推理系统。
home-subtitle: Shuhao Zhang &ensp;|&ensp; 张书豪
